version: '3.8'
services:
  php:
    build: .
    ports:
      - 8090:80
    volumes:
      - ./src:/var/www/html
  
  mysql:
    image: mysql
    restart: always
    ports:
      - 8806:3306
    volumes:
      - ./db:/var/lib/mysql
    
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: 'receitas'
      MYSQL_USER: 'recipe'
      MYSQL_PASSWORD: 'recipe@23'

volumes:
  php:
  mysql: